name: kdbx
description: KeepassX format implementation in pure dart. (kdbx 3.x and 4.x support).
version: 2.4.0
homepage: https://github.com/authpass/kdbx.dart
publish_to: none

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  logging: '>=0.11.3+2 <2.0.0'
  crypto: '>=2.0.0 <4.0.0'
  pointycastle: '>=3.4.0 <4.0.0'
  xml: '>=4.4.0 <7.0.0'
  uuid: ^4.0.0
  meta: '>=1.0.0 <2.0.0'
  clock: '>=1.0.0 <2.0.0'
  convert: '>=2.0.0 <4.0.0'
  isolates: '>=3.0.0 <4.0.0'
  path: '>=1.6.0 <2.0.0'
  quiver: '>=2.1.0 <4.0.0'
  archive: '>=2.0.13 <4.0.0'
  supercharged_dart: '>=1.2.0 <4.0.0'
  synchronized: '>=2.2.0 <4.0.0'

  collection: '>=1.15.0 <2.0.0'

  # required for bin/
  args: '>1.5.0 <3.0.0'
  logging_appenders: '>=0.1.0 <2.0.0'
  dargon2:
    git:
      url: https://github.com/GlitterWare/dargon2.git
      path: dargon2
      ref: 180ec98990f8e1d7190a34f2c131e9d587d1a4ff
  dargon2_interface: ^1.1.1
  dargon2_flutter_mobile: ^3.3.0
  dargon2_flutter_desktop: ^3.2.0


dev_dependencies:
  flutter_lints: '>=2.0.0 <3.0.0'
  test: '>=1.6.0 <2.0.0'
  fake_async: ^1.2.0
